### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by SidRoberts** [SidRoberts/phalcon-cron#7]

**Comment by ibpavlov** [comment]
@SidRoberts Could you make another version for this repo? 
I wanted to switch to the last stable version in my production environment, but it only broke my jobs because of the differences in the code. And I think that the latest usage is better. Maybe the code won't change soon, but you never know. Thanks in advance.

**Comment by SidRoberts** [comment]
I've tagged the latest commit as 'v0.2' and I'll be working on this today to hopefully overhaul the codebase and release version 1. I'll update this PR thread when I'm done so you can check it out.

**Comment by ibpavlov** [comment]
Great, Thank you.

**Comment by SidRoberts** [comment]
Fixed https://github.com/SidRoberts/phalcon-cron/releases/tag/v1.0.0
